function spikePlot = spikes_pos_vs_phase
spikePlot.x = 'pos_linearized';
spikePlot.y = 'theta_phase';
spikePlot.x_label = 'Position (cm)';
spikePlot.y_label = 'Theta phase';
spikePlot.state = '';
spikePlot.filter = 'speed';
spikePlot.filterType = 'greater than';     % [none, equal to, less than, greater than]
spikePlot.filterValue = 20;
spikePlot.event = '';
spikePlot.eventType = '';             % [events,manipulation,states]
spikePlot.eventAlignment = 'peak';         % [onset, offset, center, peak]
spikePlot.eventSorting = 'amplitude';      % [none, time, amplitude, duration]
spikePlot.eventSecBefore = 0.2;            % in seconds
spikePlot.eventSecAfter = 0.2;             % in seconds
spikePlot.plotRaster = 0;
spikePlot.plotAverage = 0;
spikePlot.plotAmplitude = 0;
spikePlot.plotDuration = 0;
spikePlot.plotCount = 0;
